### ISSUE TITLE
.pypit files need to be updated

### ISSUE THREAD

**Issue by jhennawi** [PYPIT/PYPIT-development-suite#27]
The development suite currently crashes because of the line: 

run spectrograph lris_red

This should be changed to: 

run spectrograph keck_lris_red

As the name of the instrument appears to have changed in the settings file, etc.

**Comment by rcooke-ast** [comment]
I think this might have been done already. Please check that you have checked out the master branch of PYPIT, arclines, and the development suite. There was a recent simultaneous overhaul of these three packages
